import pandas as pd
import streamlit as st
from sqlalchemy import text
from config.db import get_engine

DASHBOARD_SQL = """
SELECT SUBSTR(DC_NAME,1,4) AS DC, DC_NAME, DATE_PST,
       NATIONAL_CHAIN, NATIONAL_CHAIN_DESC,
       SUM(SAP_ORDER) AS SAP_ORDER,
       SUM(SAP_RECEIVED_LINES) AS SAP_RECEIVED_LINES,
       SUM(SAP_CONFIRMED_LINES) AS SAP_CONFIRMED_LINES,
       SUM(SAP_REJECTED_LINE) AS SAP_REJECTED_LINE,
       SUM(SAP_DELIVERIES_PGI_COMPLETE) AS SAP_DELIVERIES_PGI_COMPLETE,
       SUM(INVOICES_CREATED_IN_SAP) AS INVOICES_CREATED_IN_SAP,
       SUM(NON_ZERO_DOLLAR_INVOICES) AS NON_ZERO_DOLLAR_INVOICES,
       SUM(ZERO_DOLLAR_INVOICES) AS ZERO_DOLLAR_INVOICES,
       SUM(SAP_DELIVERY_COUNT) AS SAP_DELIVERY_COUNT,
       SUM(ACUMAX_DELIVERY_COUNT) AS ACUMAX_DELIVERY_COUNT,
       SUM(RELEASED_COUNT) AS RELEASED_COUNT,
       SUM(PICK_COUNT) AS PICK_COUNT,
       SUM(PGI_COUNT) AS PGI_COUNT,
       SUM(TRUCK_CLOSURE_COUNT) AS TRUCK_CLOSURE_COUNT,
       SUM(DIFFERENCE) AS DIFFERENCE
FROM POLCAI.SAP_ORDER_VS_ACUMAX_KPI
WHERE DC_NAME IS NOT NULL
GROUP BY SUBSTR(DC_NAME,1,4), DC_NAME, DATE_PST,
         NATIONAL_CHAIN, NATIONAL_CHAIN_DESC
ORDER BY DATE_PST DESC, DC_NAME
"""

@st.cache_data(ttl=3600, show_spinner=False)
def load_dashboard_data() -> pd.DataFrame:
    with get_engine().connect() as connection:
        return pd.read_sql(text(DASHBOARD_SQL), connection)
